### ISSUE TITLE
新增免费商用字体【演示佛系体】

### ISSUE THREAD

**Issue by CheneyLin** [KonghaYao/chinese-free-web-font-storage#10]
https://www.thosefree.com/slidefu

演示佛系体由纪国才老先生授权，由 Keynote 研究所和秋叶 PPT 联合发布，面向全社会发布的免费商用字体，所有个人和商业机构都可以下载免费使用。

个人备用链接
链接: https://pan.baidu.com/s/1kKOnzGxpgU8LefD0QmaIwQ 提取码: caxf 复制这段内容后打开百度网盘手机App，操作更方便哦

特来致意！

我在个人项目 DevShots 中使用了，效果不错。

https://www.gpwzw.com/

**Comment by KonghaYao** [comment]
演示佛系体已添加，感谢您的建议
https://chinese-font.netlify.app/fonts/ysfxt/slidefu-regular/
![image](https://github.com/KonghaYao/chinese-free-web-font-storage/assets/68177907/259e5fbd-0c07-4ba4-8b68-57f0734dd03f)
