### ISSUE TITLE
【字体请求】——隶书

### ISSUE THREAD

**Issue by y377** [KonghaYao/chinese-free-web-font-storage#27]
> 不错的项目，感谢！

请问能否添加一个开源免费可以商用的隶书字体？做的项目基本全是简体汉字，文章中偶有中文数字和英文数字，没有英文字母。
隶书字体尽可能中规中矩，再次感谢！

**Comment by KonghaYao** [comment]
如果需要添加字体的话，必须要找到相应的实际字体的喔。找到之后，我们这边可以帮您添加。
