### ISSUE TITLE
请支持装甲明朝体

### ISSUE THREAD

**Issue by isPoto** [KonghaYao/chinese-free-web-font-storage#31]
另外，在线字体分包器，我点击是 404

https://chinese-font.netlify.app/#:~:text=%F0%9F%8D%95-,%E5%9C%A8%E7%BA%BF%E5%AD%97%E4%BD%93%E5%88%86%E5%8C%85%E5%99%A8,-%E5%BC%80%E6%BA%90%E4%BB%93%E5%BA%93

**Comment by KonghaYao** [comment]
https://chinese-font.netlify.app/online-split/
哎呀，链接填错了，使用上面这个即可
