### ISSUE TITLE
想看您所有前端作品

### ISSUE THREAD

**Issue by isPoto** [KonghaYao/chinese-free-web-font-storage#32]
您说自己是国风前端开发者，我看了您的中文网字和古诗两个网站，确实是设计风格鲜明的网页

我很喜欢您的设计，我想看更多，比如未公开或您曾经开发过的作品。

如需保密，可签署保密协议，请务必让我看您作品

通过您项目，我开发了一个打字方案的配套软件网页，感谢您！

https://singbit.pages.dev/singbitK

**Comment by KonghaYao** [comment]
感谢您的支持，最近比较忙于工作和处理中文网字计划的工具构建，在设计方面的作品暂时只有这两份。不过，后面有计划过设计一个关于三星堆青铜器风格的页面。我本人的工作是前端工程师，工作的话较为繁忙，中文网字计划的技术基础方面也有颇多需要更新的东西，就没有很多设计上的时间了。在忙完一批基础工作之后，估计会有更多的新国风页面。

**Comment by isPoto** [comment]
你过去的作品呢？

希望中文字网支持用户上传字体托管

**Comment by KonghaYao** [comment]
中文网字不会实现用户上传字体托管的，虽然我之前做过一版本，但是考虑到审核字体授权相关的事情将会非常麻烦，就没有继续去做了

**Comment by isPoto** [comment]
那我想加入呢？我自证字体是可商用，然后部署。

或者我列清单你部署字体？

**Comment by KonghaYao** [comment]
可以列出字体的在线 URL，或者按着 PR 的流程发到 github 上
<img width="983" alt="image" src="https://github.com/KonghaYao/chinese-free-web-font-storage/assets/68177907/e7434b1b-5a78-4d4c-bc4e-d1fb44b6cc23">

**Comment by KonghaYao** [comment]
如果你列出请求的话，可以提一个 PR 在 README 里面写上你的贡献，这样 github 就有贡献者记录了
