### ISSUE TITLE
你如何解决「在 css 文件中智能提示 html 中的类名」？

### ISSUE THREAD

**Issue by isPoto** [KonghaYao/chinese-free-web-font-storage#36]
我事先编写好 html 文件

然后再写 css ，但 css 文件中不会智能提示同名 html 文件中定义好的 class / id 名，我只能手动输入

查了下目前并没有相关的解决扩展，基本都是 html 文件智能提示链接的 css 类名

或者全选 html 文件后输入命令调用生成所有类名的 css 文件

你怎么解决这个问题

**Comment by KonghaYao** [comment]
一般指使用少数字体的话，就直接查找 css 文件上标记的 font family
如果需要动态更换的那种，类似首页的动态更换的，中文网字计划调用了 index.json 去查询整个项目的包，然后抽取出 font family 和 css 文件地址

**Comment by KonghaYao** [comment]
IDE 我也没有使用过什么插件会去读 css 中的 font family
