### ISSUE TITLE
【添加字体】目哉像素体、全小素、“粗柳坊字库” 三套字体

### ISSUE THREAD

**Issue by diaowinner** [KonghaYao/chinese-free-web-font-storage#38]
永久链接：
- https://github.com/DWNfonts/MuzaiPixel/raw/main/MZPXorig.ttf
- https://github.com/DWNfonts/MuzaiPixel/raw/main/MZPXflat.ttf
- https://diaowinner.itch.io/chusung/purchase
- https://diaowinner.itch.io/lyusung/purchase
- https://diaowinner.itch.io/fonsung/purchase
- https://diaowinner.itch.io/taipei-fonts/purchase
- https://diaowinner.itch.io/galmuri-extended/purchase

如果出现中间页面，直接点击“No thanks, just take me to the downloads”，然后下载。

都是 OFL（或兼容 OFL）的

**Comment by KonghaYao** [comment]
收到，这些字体将会在这周内进行上线发布嘞 @diaowinner

**Comment by KonghaYao** [comment]
1. 目哉像素体、全小素 已上线
2. “粗柳坊字库” 由于技术原因，在处理 BUG
@diaowinner

**Comment by KonghaYao** [comment]
粗、坊两个字体包是使用了特殊的特性吗，harfbuzz 解析这两个字体的时候报错了，但是柳宋是可以的 @diaowinner

**Comment by diaowinner** [comment]
奇怪了
那就拿随便一个字体编辑器重新导出一个？
（说一下粗柳坊字库就是玄学弄出来的玩意（（

**Comment by KonghaYao** [comment]
harfbuzz 解析不了这三个字体，估计是底层的 opentype 数据的问题

**Comment by diaowinner** [comment]
行吧，等我有时间去试试
另外别开 issue 给 harfbuzz 了，我承认是我字体的问题（（
