### ISSUE TITLE
 网站字体列表页，safari 无法预览

### ISSUE THREAD

**Issue by xorange** [KonghaYao/chinese-free-web-font-storage#44]
问题：

在[网站字体列表页](https://chinese-font.netlify.app/#font-list)，safari 无法预览，字体列表栏白屏

如下：
![image](https://github.com/KonghaYao/chinese-free-web-font-storage/assets/441600/c81ce0a1-4d4b-4c7d-a117-1e2dcb3010e9)

鼠标悬停有效果

环境：
MacOS 14.3.1 (23D60)
Safari 17.3.1 (19617.2.4.11.12)

Workaround：
目前暂时通过 inspect element 解决……

**Comment by KonghaYao** [comment]
ok，safari 不支持部分比较新的 CSS API 导致动画挂载在第一帧，从而白了，已经修复了
