### ISSUE TITLE
「黄令东齐伋体」预览中的奇怪状况

### ISSUE THREAD

**Issue by fr1g** [KonghaYao/chinese-free-web-font-storage#45]
<img width="1279" alt="image" src="https://github.com/KonghaYao/chinese-free-web-font-storage/assets/53085628/4964965b-9a56-4cf0-a7e7-504bbfe42f16">
看起来是有一个svg, 但是元素选择里全是margin了
<img width="1792" alt="image" src="https://github.com/KonghaYao/chinese-free-web-font-storage/assets/53085628/94e0772a-d6de-4ae4-9069-a38077d96ffd">

**Comment by fr1g** [comment]
<img width="582" alt="image" src="https://github.com/KonghaYao/chinese-free-web-font-storage/assets/53085628/21c76e71-38dc-4427-93e5-aa2b1544c618">
这二位怎么预览没有了, <del>是safari兼容问题吗</del> 好像不是, edge里也一样, 并且排除了本机代理设置的问题.

**Comment by fr1g** [comment]
<img width="344" alt="image" src="https://github.com/KonghaYao/chinese-free-web-font-storage/assets/53085628/dbe19de1-a83b-42b2-8477-9ace25700355">
附上一些f12内容

**Comment by KonghaYao** [comment]
ok, 正在找 bug 中

**Comment by KonghaYao** [comment]
![image](https://github.com/KonghaYao/chinese-free-web-font-storage/assets/68177907/5fb8cc55-ed5d-4bef-883f-d53a4e426982)
全小素已回归，预览的回去看看

**Comment by KonghaYao** [comment]
<img width="765" alt="image" src="https://github.com/KonghaYao/chinese-free-web-font-storage/assets/68177907/05644c21-2c18-404c-9f81-f03d0b627207">
对 cn-font-split 的图片生成进行爆改，修复了针对换行符和部分字形的显示情况，这款字体比较特殊，其没有英文字体，故显示 fallback 字符确实是正确的
