### ISSUE TITLE
CDN是炸了吗

### ISSUE THREAD

**Issue by nowscott** [KonghaYao/chinese-free-web-font-storage#49]
今天在测试的时候发现你们cdn的网页找不到了，好想用朱雀仿宋还有京华老宋体啊

**Comment by KonghaYao** [comment]
您好，CDN 服务已经恢复了。CDN 导航到另一个新的存储地址导致 404 了，现在您可以通过 
https://chinese-fonts-cdn.deno.dev/chinesefonts3/packages/zqfs/dist/ZhuqueFangsong-Regular/result.css
访问到朱雀仿宋的 CSS 地址，如果不生效，那么可以尝试刷新一下浏览器。 @nowscott

**Comment by nowscott** [comment]
好的谢谢

**Comment by nowscott** [comment]
> 您好，CDN 服务已经恢复了。CDN 导航到另一个新的存储地址导致 404 了，现在您可以通过 https://chinese-fonts-cdn.deno.dev/chinesefonts3/packages/zqfs/dist/ZhuqueFangsong-Regular/result.css 访问到朱雀仿宋的 CSS 地址，如果不生效，那么可以尝试刷新一下浏览器。 @nowscott

但是网站的网址还没有修复是吧

**Comment by nowscott** [comment]
> 您好，CDN 服务已经恢复了。CDN 导航到另一个新的存储地址导致 404 了，现在您可以通过 https://chinese-fonts-cdn.deno.dev/chinesefonts3/packages/zqfs/dist/ZhuqueFangsong-Regular/result.css 访问到朱雀仿宋的 CSS 地址，如果不生效，那么可以尝试刷新一下浏览器。 @nowscott

奇怪我使用chrome就访问不了

**Comment by KonghaYao** [comment]
那就是缓存生效了吧, 可以用隐私模式试试看嘞

**Comment by KonghaYao** [comment]
浏览器 F12 执行
`fetch('https://chinese-fonts-cdn.deno.dev/chinesefonts3/packages/zqfs/dist/ZhuqueFangsong-Regular/result.css',{cache:"no-cache"})` 应该也是可以清缓存的

**Comment by nowscott** [comment]
> 浏览器 F12 执行
> `fetch('https://chinese-fonts-cdn.deno.dev/chinesefonts3/packages/zqfs/dist/ZhuqueFangsong-Regular/result.css',{cache:"no-cache"})` 应该也是可以清缓存的 

好的，等下我试一下
