### ISSUE TITLE
希望可以加入阿里妈妈的这几款免费字体

### ISSUE THREAD

**Issue by mancuoj** [KonghaYao/chinese-free-web-font-storage#5]
https://www.iconfont.cn/fonts/index

**Comment by KonghaYao** [comment]
由于 阿里妈妈的那个证书 是有说明转换需要授权，先问问官方吧
![image](https://github.com/KonghaYao/chinese-free-web-font-storage/assets/68177907/ba4a3b33-f64c-4bb5-a7f9-d4c0b19965f4)
