### ISSUE TITLE
YuFanXinYu was not uploaded to npmjs

### ISSUE THREAD

**Issue by xxnuo** [KonghaYao/chinese-free-web-font-storage#56]
Thank you very much for your work.
YuFanXinYu is a nice font,
The [home page](https://chinese-font.netlify.app/#font-list) shows all font types of same on yfxy font in the list and are not uploaded to npmjs.
Can you upload it lol

**Comment by KonghaYao** [comment]
https://www.npmjs.com/package/@chinese-fonts/yfxy?activeTab=readme
您好，已经上传至 npm 了
