### ISSUE TITLE
【添加字体】寒蝉端黑体

### ISSUE THREAD

**Issue by illusate** [KonghaYao/chinese-free-web-font-storage#57]
寒蝉端黑体是思源黑体的宽体和窄体版本，重新插值生成，没做其他任何改变。
https://github.com/Warren2060/ChillDuanSans
https://github.com/Warren2060/ChillDuanSans/blob/main/License
（比较希望有 widesemibold 字重）
谢谢

**Comment by KonghaYao** [comment]
这款字体并没有 widesemibold 字重哦，只有宽体和窄体哦
