### ISSUE TITLE
【添加字体】飞花宋体

### ISSUE THREAD

**Issue by Lin0u0** [KonghaYao/chinese-free-web-font-storage#58]
仓库地址： https://github.com/Skr-ZERO/FlyFlowerSong
授权信息：根据字形维基的[著作权与许可协议](http://zhs.glyphwiki.org/wiki/GlyphWiki:%e8%91%97%e4%bd%9c%e6%9d%83%e4%b8%8e%e8%ae%b8%e5%8f%af%e5%8d%8f%e8%ae%ae)，任何人都可以自由使用在字形维基（GlyphWiki）提交的字形数据及文章内容。不论一切针对数据的改变或商业用途，任何人都可以自由地使用、复制甚至转载上述的一切数据和内容。本字体遵循上述授权信息。

**Comment by KonghaYao** [comment]
ok, 这周末版本更新上哈 @Lin0u0

**Comment by KonghaYao** [comment]
@Lin0u0 飞花宋体已经更新到主站及 CDN 中 
<img width="1074" alt="image" src="https://github.com/KonghaYao/chinese-free-web-font-storage/assets/68177907/6b3f8758-5961-47bc-b37f-5da6424853ba">
