### ISSUE TITLE
建议将下面中的 index.json 发布到 npm

### ISSUE THREAD

**Issue by miantiao-me** [KonghaYao/chinese-free-web-font-storage#60]
想在网站做切换字体功能，需要使用 https://github.com/KonghaYao/chinese-free-web-font-storage/blob/branch/index.json 文件。

目前只能复制，直接安装 git 下面有很大拖慢打包速度。

建议将此项目也发布到 NPM, 忽略字体目录和文件，main 指向 index.json

**Comment by KonghaYao** [comment]
@chinese-fonts/index 这个仓库现在是提供构建索引了
另外，https://chinese-font.netlify.app/font-list.json 这个接口总是最新的数据。 @ccbikai

**Comment by miantiao-me** [comment]
JSON 信息中缺少 fontFamily 信息

比如 斗鱼追光体 对应 "DOUYU Font"

**Comment by KonghaYao** [comment]
@ccbikai 涉及到具体的 css 信息的话，需要改动一下构建流程，今天应该能完成

**Comment by KonghaYao** [comment]
@ccbikai  @chinese-fonts/index 1.2.0 版本及线上接口都更新了 css 相关的信息
<img width="907" alt="image" src="https://github.com/user-attachments/assets/4c459716-568e-469b-9edd-d07672304fcb">

**Comment by miantiao-me** [comment]
十分感谢， 已经用上了 https://github.com/javayhu/haitang/pull/6
