### ISSUE TITLE
【添加字体】LXGWBright GB | LXGWBright TC

### ISSUE THREAD

**Issue by Paxton-PKJ** [KonghaYao/chinese-free-web-font-storage#65]
LXGWBright为原霞鹜文楷字体中文部分与Ysabeau Office 西文结合字体

字体：https://github.com/lxgw/LxgwBright
许可SIL Open Font License 1.1：https://github.com/lxgw/LxgwBright/blob/main/license.txt

特别喜欢霞鹜文楷的中文以及 Ysabeau Office 的西文，希望添加，谢谢

**Comment by KonghaYao** [comment]
可，周四晚上将会发版

**Comment by KonghaYao** [comment]
已经添加，可以官网首页查看哈 @Paxton-PKJ
