### ISSUE TITLE
得意黑中的阿拉伯数字9好像有点问题

### ISSUE THREAD

**Issue by macshen** [KonghaYao/chinese-free-web-font-storage#7]
如题

**Comment by KonghaYao** [comment]
对的，这个是由于旧版本分包的原因，新版本已经解决，如果你的浏览器还是没有变化的话，可能是强制缓存的缘故，清理缓存之后可以看到新版本。
新版本还有一个毛病：竖排重叠。
经过几个小时的排查，貌似是得意黑的字体的设置问题，被分包过后就会导致字符竖向间距消失，从而重叠。但是其它的类似字体分包就没有这个问题😂

**Comment by KonghaYao** [comment]
针对于 竖排重叠问题，属于字体内部的设置错误了，可以采用 css 中的 letter-spacing: 1.1em 解决，属于临时性办法😂
