### ISSUE TITLE
SIL OFL 协议不支持保留原字体名的情况下进行子集化

### ISSUE THREAD

**Issue by GuuuWei** [KonghaYao/chinese-free-web-font-storage#8]
参照 OFL FAQ的2.6
https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL-FAQ_web#b4b7db21

建议在子集化的时候，字体名加后缀混淆名
如 Fontname_94bae3

**Comment by KonghaYao** [comment]
您好，我个人认为中文网字计划的情况属于对原始字体的修改，但是符合于 Functional Equivalence (FE，功能等效性), 应该可以使用 RFNs (Reserved Font Names,保留字体名称)。也就是基于 2.7 的讨论，但是其中的 `a web font `存在歧义（一个网络字体文件 or 一个网络字体版本），我认为是整个网络字体而非单独的字体分包文件。以下为我的思考：
1. 中文网字计划采用的字体子集化方案是全量级子集化，所有的字体都可以在网页中进行使用和展示，这点可以在单独字体页面的编辑框内实现。
2. 同时，字体字形为原始字体版本，采用 harfbuzz 分包和 woff2 压缩，在表现上无差异，形态为一致。
3. 整个字体子集分包不具有网络字体外的通用性，即子集难以合成为单个桌面端可用的字体的分包，因此符合 RFNs 的，并与原始字体作者属性无冲突。
4. 中文网字计划所构建的字体及其css，保留原始字体的所有元数据，其声明于每个文件内部，保护原始作者权益，其直接由软件复制，并未进行修改。

基于上面的情况，我个人认为可以采用 RFNs。但是由于 OFL 没有原文声明这种情况，所以后面发布版本时，应该会采用您的混淆方案😄。

![image](https://github.com/KonghaYao/chinese-free-web-font-storage/assets/68177907/f1a0807c-28cc-4b63-a4d8-9b48e09f8ceb)

![image](https://github.com/KonghaYao/chinese-free-web-font-storage/assets/68177907/461e06ee-5326-4cea-a49d-ad01cd9ea2a8)

![image](https://github.com/KonghaYao/chinese-free-web-font-storage/assets/68177907/ddbfcad4-0a66-49d0-b028-10bbeaf85e75)

**Comment by GuuuWei** [comment]
FE 功能等效性还是很复杂的，特别是Kerning、Opentype、合字、私有区这类问题
比如猫啃什锦黑的合字丢失
禁⃝

![image](https://github.com/KonghaYao/chinese-free-web-font-storage/assets/11283300/0d30d8c4-8f4c-401e-875a-bb924630377c)
![image](https://github.com/KonghaYao/chinese-free-web-font-storage/assets/11283300/5abe2943-6e1b-4244-bbf2-bfd17ded5f01)

**Comment by KonghaYao** [comment]
哎，发生这种情况的原因是 两个字体不在一个包内，所以浏览器识别不到另外的合字字体，这个严格来说可以避免，但是涉及到非常底层的 C++ 代码和字符分配，就比较难搞了。但是我测试过分配到同一个包，这个合字是可以实现的😂。

**Comment by GuuuWei** [comment]
我的建议是不要碰这些部分，混淆字体名就足够了
抓大放小，专注解决中日韩环境下的 Web Font 分包就好，这个价值很大

**Comment by KonghaYao** [comment]
分包软件也是我维护的，所以涉及到 feature 的东西我都要去解决😂。
名称混淆这个其实很容易的，在cn-font-split 中添加一个random 的 fontFamily 即可
这个其实功能早有了，只是采用默认字体名好管理，如果所有文件更改发版的话，那得周末才有时间推到 cdn

**Comment by KonghaYao** [comment]
最新版本重新打包和支持了复杂字形等 feature。由于网站被攻击，CDN 盗用，将优先处理功能性问题，授权问题将在之后进行解决😭
![image](https://github.com/KonghaYao/chinese-free-web-font-storage/assets/68177907/36c361be-a6cf-47cc-8d63-99fcb6074510)
