### ISSUE TITLE
新免费商用字体「京華老宋体」

### ISSUE THREAD

**Issue by Ouxxxxxjoe** [KonghaYao/chinese-free-web-font-storage#9]
字体作者：TeririW
介绍页：https://zhuanlan.zhihu.com/p/637491623
下载 ：https://drive.google.com/file/d/1WQu8_LaS5JRn9Fd03cxWpT4LA9H9HC7T/view?pli=1

项目上好像没有添加字体的入口，只能在 GitHub 上吗？

**Comment by KonghaYao** [comment]
非常感谢您的推荐，由于网站正在处理 CDN 盗用问题，故暂停添加字体，优先处理 BUG😂。
对于添加字体，将在处理完成紧急任务之后进行，完成时，将会在这个 issues 反馈。

**Comment by KonghaYao** [comment]
京华老宋体已经添加，感谢您的建议
https://chinese-font.netlify.app/fonts/jhlst/%E4%BA%AC%E8%8F%AF%E8%80%81%E5%AE%8B%E4%BD%93v1_007/
![image](https://github.com/KonghaYao/chinese-free-web-font-storage/assets/68177907/781f3fca-880e-495e-ad6e-022ae2671a99)

**Comment by Ouxxxxxjoe** [comment]
感谢，已将网站投稿至网站导航，好消息是已经收录了一段时间，祝好。
